### ISSUE TITLE
Crash when exploring new dungeon/maps

### ISSUE THREAD

**Issue by kusayu** [spoorn/myLoot#20] opened 2022-06-06 04:28 UTC
**Modloader:**
Fabric 1.18.2 ver 0.14.5

**Modpack**
AQM2

this is the crashlog

[message.txt](https://github.com/spoorn/myLoot/files/8841885/message.txt)

**Comment by spoorn** [comment] 2022-06-08 07:33
That's not due to myLoot.  myLoot is just in the error log because myLoot hangs the server thread waiting for the chunk a lootable container is in to finish loading - but the root cause is something else has caused a chunk to not load within the Minecraft Watchdog timeout, which defaults to 1 minute for a single tick.

See https://github.com/spoorn/myLoot/issues/17 and https://github.com/spoorn/myLoot/issues/16

I can look into some auto timeout logic, but it won't fix the root issue which is some chunk failed to load.  Even without myLoot, you may still see crashes or performance issues.

Closing this in favor of https://github.com/spoorn/myLoot/issues/17

**Closed by spoorn** 2022-06-08 07:33 UTC
