### ISSUE TITLE
[1.18.2] Performance Issues

### ISSUE THREAD

**Issue by itsdinkd** [spoorn/myLoot#17] opened 2022-05-01 22:38 UTC
https://spark.lucko.me/JLF1MDTfyn

**Comment by spoorn** [comment] 2022-05-02 00:09
What's the specific performance issue are you talking about?  What actually is happening in game (freezing, or just lag, etc.)? 

The spark log you gives me which expands out to the myLoot replacer is a red herring.  If you see below when you expand it out, all it's doing is "waiting" calling LockSupport.parkNanos().  myLoot has to replace loot containers with the myLoot variant, but for that, it requires calling World.setBlockState() which waits until the **chunk that the loot container is in is done being generated**.  If the server thread is spending all its time waiting there, that means that specific chunk is taking that long to generate/load.  

If your game is freezing and crashes, and that's when you got that spark log, then it means something has caused that chunk to never be able to load  (which I've seen happened with the [Unstructured mod](https://github.com/spoorn/myLoot/issues/16)).

If your game is lagging and then eventually unfreezes itself, then it's just taking a long time for that chunk to load (which is also probably due to some other mod).

One thing I could try to do is time out the loot container replacement so it only spends some configurable **maxTime** before giving up on replacing a chest - but this means this isn't fixing the actual problem which is that chunk either not being able to load or taking a very long time and myLoot doesn't modify any chunk loading.

The spark log you gave only shows the Server Thread.  Chunk loading is done on a separate thread, so if you have the full spark log showing all other threads, maybe we can dig into what is causing chunk loading to freeze/lag

![image](https://user-images.githubusercontent.com/12925899/166169981-fd725e0b-a708-42d8-8122-d80b733a68b7.png)

**Comment by itsdinkd** [comment] 2022-05-04 08:01
This was taken from our server with multiple people in it, MSPT was getting hit / low tps.

**Comment by spoorn** [comment] 2022-05-04 09:24
Without the full thread dump, no one can tell what is causing chunk loading to take so long.  myLoot isn't doing anything **active**, it's simply sleeping on the server thread, waiting for the chunk to be loaded.  

I can try to look into some sort of timeout handling and not hold the server thread waiting for the chunk to be loaded, but it can cause weird issues like a player might see the regular chest and then it suddenly turns into a myLoot container - which is why I didn't want to do this initially.  I'd have to try stuff out and test this

The root issue is **not due to myLoot** however, as some other mod or minecraft itself is taking a long time to load one of the chunks. 

What command are you running spark with?  There is a `--thread *` argument that will make spark track all threads, not just the ServerThread: https://spark.lucko.me/docs/Command-Usage.  You could try running that and it might output all the threads.  One of them should be a thread that's loading chunks and then you might see why it's taking >11 seconds to load a single chunk

**Comment by itsdinkd** [comment] 2022-05-07 20:40
im using /spark profiler, no arguments. 

I'll try what you suggested trying to get all the threads. 

Please stand by

**Comment by itsdinkd** [comment] 2022-05-08 01:57
https://spark.lucko.me/HqcVgNPocm

**Comment by spoorn** [comment] 2022-05-09 00:24
I don't see myLoot in either of those spark logs.  Do you still have myLoot installed on the server?  If so, then it's a bit more proof of what I said above that myLoot isn't the **_root cause_** of your lag spikes because myLoot only hangs the server thread when it needs to replace loot containers -> which only happens if a chunk being loaded includes loot containers -> which needs to wait for chunk loading to finish.

The chunk loading thread is normally on the Worker-Main threads, but usually there should be quite a few of them - your spark logs only show 1.  I'm not sure why that is, maybe some other mod put chunk loading on another thread? 

In any case, the main server thread looks like it's taking up most of the time on ticking entities (see screenshot below).  One more thing I noticed is there are a ton of threads running during your spark profiling.  If your CPU doesn't have that many cores, having so many threads up on a single machine may degrade performance due to context switching - especially since it looks like most of these threads just wait and do nothing else.


![image](https://user-images.githubusercontent.com/12925899/167321293-e2bcf24b-0d0b-491a-a7a4-d378d667ba24.png)

**Comment by spoorn** [comment] 2022-06-19 07:59
@itsdinkd 

I tried looking into this a bit more.  I wonder if this change I made would help any bit.  If you want, you could try the newer version I just uploaded (2.1.1-1.18): https://www.curseforge.com/minecraft/mc-mods/myloot/files/3838376

**Comment by itsdinkd** [comment] 2022-06-19 17:45
Honestly i havent seen much performance issues lately from MyLootr

**Comment by itsdinkd** [comment] 2022-06-19 17:45
if its a server side change only, I can put it in the official servers though, if it requires on client, that will be more difficult

**Comment by spoorn** [comment] 2022-06-19 23:27
@itsdinkd That's good, as I mentioned before, that probably means whichever mod that was causing chunkloading to slow down isn't doing it anymore or hasn't happened. 

The update is server-side only, but if your server is working fine now, keep it that way :)

**Comment by spoorn** [comment] 2022-06-19 23:48
I'll close this issue for now.  Feel free to reopen if issue comes back

**Closed by spoorn** 2022-06-19 23:48 UTC
Labels: enhancement, due to other mod

**Comment by spoorn** [comment] 2022-06-27 22:08
@itsdinkd I found out how to fix the issue in the latest version!  Do update when you can as it should greatly help improve server TPS - at least when myLoot was in play

**Comment by itsdinkd** [comment] 2022-07-08 20:06
Thank you, updating now :)
